---
name: npm-test
on: push
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: npm ci
    - name: test
      run: npm test
  deploy:
    needs: npm-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: npm ci
    - name: build
      run: npm run build
    - name: deploy
      run: echo "Deploying ..."
