---
name: npm-test
on: push
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: npm ci
    - name: test
      run: npm test
